name: iAuction
main: couk.rob4001.iauction.iAuction
version: 5.0.0
author: Rob4001
description: Auctions for iConomy plugin for Bukkit Original by Zazara107
depend: [Vault]
commands:
  auction:
    description: Manages auctions
    usage: /<command> help - show auctions help