name: iAuction
main: couk.rob4001.iAuction.iAuction
version: 5.0.0
author: Rob4001
description: Auctions for Bukkit Original by Zazara107
commands:
  auction:
    description: Manages auctions
    usage: /<command> help - show auctions help